# main.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Maven Integration
        uses: ./.github/workflows/maven.yml

      - name: SonarQube Analysis
        uses: ./.github/workflows/sonarqube.yml

